### PR TITLE
Fixes user sort problems on people index.

### LINKED ISSUE #1867: Download option in Image Viewer doesnt work
### Descriptive summary

In the current version of Scholar@UC based on Hyrax 1.x the is a download button in the image viewer.  It doesn't worked.  This may be improved or resolved in Hyrax 2.x where the Image Viewer is incorporated into the release.  

### Expected behavior
Download button gives options for size, and then allows the user to export an image.

### Actual behavior
A message appears that says "No download options are available."

### Steps to reproduce the behavior

Go to a work with an image, such as https://scholar.uc.edu/show/bc386t80f
Select the download button in the lower left-hand corner of the image viewer.

### Related work
Public files can be downloaded from the file listing further down on the work show page.  An adequate solution may be to suppress this button.

### LINKED ISSUE #1868: Improve UX of People Listing
### Descriptive summary

The People listing should be reviewed for UX.  See https://scholar.uc.edu/users?locale=en

It's not clear that the user name and user email are linked to the user profile.

Issue #1895 covers
The sort options on the People display don't fully work and it is not clear which columns can be sorted.
"Contributor" could be a better column header than "User Name."

~When paging through the People display, an inconsistent number of names are shown - this may be a side effect of hiding users with zero works.~ (Split into issue #1883)

~The People listing also suffers from the "infinite pagination" bug which was documented here: https://github.com/uclibs/scholar_uc/issues/1781.~ (Split into issue #1890)

### LINKED ISSUE #1895: Sort options on the People display need to work for User Name, User ID, and College & Department
### Descriptive summary

The sort options on the People display don't fully work and it is not clear which columns can be sorted.

### Expected behavior

The sort options on the People display do work for User Name and College & Department.
User ID DOES work.

The carat should show up by default if a column is sortable.

User Name column should be labelled as 'Contributor'

### Actual behavior

The sort options on the People display don't work for UserName and College & Department.
User ID DOES work.

The carat should show up by default if a column is sortable.

### Steps to reproduce the behavior

1.  Visit : https://scholar.uc.edu/users?utf8=%E2%9C%93&uq=&sort=login&locale=en
2. Click Column Header.
### Related work

https://github.com/uclibs/scholar_uc/issues/1868

### LINKED ISSUE #1897: Remove User ID from People Display
### Descriptive summary

The User ID is an email address but is providing the same function as the User Name (i.e. Contributor) column, by providing a link to the individual profile page.  The email address is provided again on the individual profile page.  We need to add the ability to suppress this information from within Scholar@UC if a student has requested privacy of records (see #1896).  One way to simplify that issue, and also clean up the People page (see #1895 and #1868) is to remove this column.  

May require further discussion with P.O.s.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #1897 
Fixes #1895 
Fixes #1868 

Present short summary (50 characters or less)

This PR covers all the issues discovered from the People listing review.

Changes proposed in this pull request:
*  Removed the User ID
*  Contributor used instead of User Name as column header.
*  Sorting (Asc/Desc) for User Name
*  Fixes pagination problems.

### CODE REVIEW

**Comment by hortongn** [comment]
@scherztc Rubocop is complaining

**Comment by hortongn** [comment]
@scherztc I think `Fixes #1867` above should be `Fixes #1897`

File: app/controllers/display_users_controller.rb [hunk 1]
```diff
@@ -24,13 +24,25 @@ def search(query)
...
 
+    def sort_value
+      sort = params[:sort].blank? ? "name" : params[:sort]
+      case sort
+      when 'name'
+        'last_name'
+      when 'name desc'
+        'last_name DESC'
+      else
+        sort
```
Comment (hortongn) [inline app/controllers/display_users_controller.rb]: @scherztc Our tests never cover the `else` case.  So line 35 is untested.  However, I don't think we have a real-world situation where `sort` is anything but 'name' or 'name desc'.  So I think the best thing to do is remove the else condition from the method.  If you want to keep the else statement, we should create a controller spec for #sort_value that verifies `sort_value` returns `params[:sort]` when `params[:sort]` is something other than "name".
